stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VENV_PATH: "$CI_PROJECT_DIR/venv"

before_script:
  - python3 -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - echo "Rodando testes..."
    - pytest tests --maxfail=1 --disable-warnings -v
  artifacts:
    when: always
    reports:
      junit: report.xml

deploy_to_github:
  stage: deploy
  script:
    - echo "Todos os testes passaram! Atualizando o GitHub..."
    - git config --global user.email "nicolasgbleal@gmail.com"
    - git config --global user.name "NicolasGayb"
    - git remote add github https://$GITHUB_TOKEN@github.com/NicolasGayb/ControleEstoqueV2.git
    - git fetch github
    - git checkout main
    - git merge origin/main --no-edit
    - git push github main
  only:
    - main
  dependencies:
    - test
