stages:
  - setup
  - test
  - deploy

# Stage de setup: prepara o ambiente
setup-job:
  stage: setup
  image: python:3.11
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Ambiente configurado"
  artifacts:
    paths:
      - venv/

# Job de testes
test-job:
  stage: test
  image: python:3.11
  dependencies:
    - setup-job
  script:
    - source venv/bin/activate
    - echo "Executando testes..."
    - pytest --maxfail=1 --disable-warnings -q

# Job de deploy
deploy-job:
  stage: deploy
  image: python:3.11
  dependencies:
    - setup-job
  before_script:
    - source venv/bin/activate
    - git config --global user.email "nicolasgbleal@gmail.com"
    - git config --global user.name "NicolasGabriel"
  script:
    - git remote add github https://$GITHUB_TOKEN@github.com/NicolasGayb/ControleEstoqueV2.git || echo "Remote github já existe"
    - git checkout main
    - git add .
    - git commit -m "Atualização automática via GitLab CI [skip ci]" || echo "Sem alterações para commitar"
    - git push github main
  only:
    - main