name: CI/CD Deploy Logistiq

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies (for validation)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Caminho do projeto
            PROJECT_DIR="/home/logistiq"
            VENV_DIR="$PROJECT_DIR/venv"

            cd $PROJECT_DIR

            # Adiciona safe directory para git
            git config --global --add safe.directory $PROJECT_DIR

            # Atualiza o código do repositório
            git reset --hard
            git pull origin main

            # Cria virtualenv se não existir
            if [ ! -d "$VENV_DIR" ]; then
              python3 -m venv $VENV_DIR
            fi

            # Ativa venv e instala dependências
            source $VENV_DIR/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Reinicia serviços (sudo NOPASSWD)
            sudo systemctl restart logistiq
            sudo systemctl restart nginx