name: CI/CD Deploy Logistiq

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests

      - name: Copy files to server via SSH
        if: success()
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/logistiq
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt

            # Rodar testes
            echo "Rodando testes..."
            pytest tests || { echo 'Testes falharam, abortando deploy!' ; exit 1; }

            # Reiniciar serviços somente se testes passarem
            sudo systemctl restart logistiq
            sudo systemctl restart nginx